import './globals.css'
import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import { Inter } from 'next/font/google'
import { QueryClientProvider } from '@tanstack/react-query'
import NextAuthSessionProvider from '@/providers/sessionProvider'

import { queryClient } from '@/providers/queryClient'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Google+Sans:wght@100;200;300;400;500;600;700;800&family=Poppins:wght@100;200;300;400;500;600;700;800&family=Roboto:wght@100;300&display=swap"
          rel="stylesheet"
        /> */}
      </head>
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <QueryClientProvider client={queryClient}>
            <Toaster richColors position="top-right" />
            {children}
          </QueryClientProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
