FROM node:20-alpine as builder

ENV NODE_ENV build

USER node
WORKDIR /home/node

COPY package*.json ./
COPY src/shared/infra/database/prisma ./prisma/
RUN npm ci

COPY --chown=node:node . .
RUN npm run build \
    && npm prune --omit=dev

# ---

FROM node:20-alpine

ENV NODE_ENV production

USER node
WORKDIR /home/node

COPY --from=builder --chown=node:node /home/node/package*.json ./
COPY --from=builder --chown=node:node /home/node/node_modules/ ./node_modules/
COPY --from=builder --chown=node:node /home/node/dist/ ./dist/

CMD ["node", "dist/main.js"]

# FROM node:18 AS builder

# WORKDIR /app

# COPY package*.json ./
# COPY src/shared/infra/database/prisma ./prisma/

# RUN npm install

# COPY . .

# RUN npm run build

# FROM node:18

# WORKDIR /app

# COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/package*.json ./
# COPY --from=builder /app/dist ./dist
# COPY --from=builder /app/prisma ./prisma

# EXPOSE 3000
# CMD [ "npm", "run", "start:migrate:prod" ]